accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .import views

app_name = 'accounts'
 
urlpatterns = [
    path('admin-login/', views.UserLoginView.as_view(), name='admin_login'),

    path('admin_logout/', auth_views.LogoutView.as_view(), name='admin_logout'),

    path('change-password/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view() ,name='password_change_done'),

    path('profile/<str:username>/', views.profile_detail, name='profile_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from ckeditor_uploader.views import upload


urlpatterns = [
    path('superuser/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('allauth.urls')),
    path('account/', include('accounts.urls', namespace='account')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('marketing/', include('marketing.urls', namespace='marketing')),
    path('admin/', include('admins.urls', namespace='admins')),

    path('ckeditor/upload/', login_required(upload), name='ckeditor_upload'),
    
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('comment/', include('comment.urls')),
    path('books/', include('books.urls', namespace='books')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from .import views

app_name = 'dashboard'

urlpatterns = [
   path('posts/', views.dashboard, name='dashboard'),
   path('profile/<int:id>/edit/', views.profile_update, name='profile_update'),
   path('reading-list/', views.reading_list, name='reading_list'),
   path('followers/', views.followers, name='followers'),
   path('following/', views.following, name='following'),
]

main/urls.py
from django.urls import path

from .import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('yesterday/posts/', views.yesterday_posts, name='yesterday_posts'),
    path('weekly/posts/', views.weekly_posts, name='week-post'),
    path('monthly/posts/', views.monthly_posts, name='month-post'),
    path('yearly/posts/', views.yearly_posts, name='year-post'),
    path('<slug:post_slug>/', views.post_detail, name='post_detail'),

    path('pages/code-of-conducts/', views.code_of_conduct, name='code_of_conduct'),
    path('pages/terms-of-use/', views.terms_of_use, name='terms_of_use'),
    path('pages/privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('pages/contacts/', views.contacts, name='contacts'),
    path('pages/about/', views.about, name='about'),
    path('pages/faq/', views.FAQ, name='faq'),
   
]

posts/urls.py
from django.urls import path

from .import views

app_name = 'posts'

urlpatterns = [
    path('write-post/', views.create_edit_post, name='create_post'),
    path('<int:id>/edit/', views.create_edit_post, name="edit_post"),
    path('<int:id>/delete/', views.delete_post, name='delete_post'),
    path('save-post-bookmark/', views.save_post_bookmark, name='save_post_bookmark'),
    path('follow/', views.follow_profile, name='follow_profile'),
    path('search/', views.search, name='search'),
    path('tags/<str:tag>/', views.post_tag_list, name='post_tag_list'),

    path('save_likes/', views.save_likes, name='save_likes'),

    path('ajax-authenticate-user/', views.ajax_authenticate_user, name='ajax_authenticate_user'),
]

accounts/models.py
import uuid
from uuid import uuid4
from django.shortcuts import reverse
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.db import models
from django_countries.fields import CountryField



class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):

        if not email:
            raise ValueError('Staff must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email,username, password=None, *args, **kwargs):

        user = self.create_user(
            email,
            username=username,
            password=password,
        )
        user.is_active = True
        is_admin=True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name='Email Address',
        max_length=255,
        unique=True,
    )
    username = models.CharField(
        verbose_name='Username',
        max_length=100,
        unique=True
    )
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_moderator = models.BooleanField(default=False)

    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email',]

    def __str__(self):
        return self.username

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.is_superuser


def profile_pic_filename(instance, filename):
    ext = filename.split('.')[1]
    new_filename = f'{uuid4()}.{ext}'
    return f'profile_pics/{new_filename}'


class Profile(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)

    following = models.ManyToManyField(CustomUser, related_name='follows', blank=True, symmetrical=False)
 
    profile_picture = models.ImageField(upload_to=profile_pic_filename, default='profile_pics/default_profile.png')
    website = models.URLField(blank=True, max_length=200)
    country = CountryField(default='TZ', verbose_name='Country')
    location = models.CharField(max_length=200)
    display_email = models.BooleanField(default=False)
    bio = models.TextField(blank=True)

    #Social media links
    youtube_link = models.URLField(verbose_name='Youtube URL', blank=True, null=True)
    facebook_link = models.URLField(verbose_name='Facebook URL', blank=True, null=True)
    instagram_link = models.URLField(verbose_name='Instagram URL', blank=True, null=True)
    linkedin_link = models.URLField(verbose_name='Linkedin URL', blank=True, null=True)
    twitter_link = models.URLField(verbose_name='Twitter URL', blank=True, null=True)
    github_link = models.URLField(verbose_name='Github URL', blank=True, null=True)

    def __str__(self):
        return self.user.username

    class Meta:
       unique_together = (("user", "following"),)

    @property
    def profiles_posts(self):
        return self.post_set.all()

    @property
    def total_follower(self):
        return self.following.count()  

    def get_absolute_url(self):
        return reverse('account:profile_detail', kwargs={'username':self.user.username})

    class Meta:
        ordering = ('-created_at',)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _
from django.db import transaction
from allauth.account.forms import SignupForm

from .models import CustomUser,Profile
from django.core.validators import RegexValidator

no_space_validator = RegexValidator(
    r' ',
    _('No spaces allowed'),
    inverse_match=True,
    code='invalid_username')

def clean_unique(form, field, exclude_initial=True, 
                 format="The %(field)s %(value)s has already been taken."):
    value = form.cleaned_data.get(field)
    if value:
        qs = form._meta.model._default_manager.filter(**{field:value})
        if exclude_initial and form.initial:
            initial_value = form.initial.get(field)
            qs = qs.exclude(**{field:initial_value})
        if qs.count() > 0:
            raise forms.ValidationError(format % {'field':field, 'value':value})
    return value

class CustomSignupForm(SignupForm):

    username = forms.CharField(required=True, label='Username',validators=[no_space_validator])

    # Override the init method
    def __init__(self, *args, **kwargs):
        # Call the init of the parent class
        super().__init__(*args, **kwargs)

        self.fields["username"].widget.attrs["placeholder"] = 'username'


    # Put in custom signup logic
    # def custom_signup(self, request, user):
    #     user_profile = Profile(user=user)
    #     user_profile.save()

    #     user.save()


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('email',)
        

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        if len(password1) < 8:
            raise forms.ValidationError('Password too short, It must be 8 character or more')
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):

    password = ReadOnlyPasswordHashField()

    class Meta:
        model = CustomUser
        fields = ('email', 'password','is_active',)

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class SignUpForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ['email', ]

class MyAuthForm(AuthenticationForm):
    error_messages = {
        'invalid_login': _(
            "Email or Password is not correct"
        ),
        'inactive': _("This account is inactive."),
    }

accounts/views.py
from django.contrib.auth.views import LoginView, LogoutView

from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.views.generic import TemplateView, CreateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from accounts.forms import SignUpForm, MyAuthForm
from accounts.models import CustomUser, Profile
from posts.models import Post

import urllib.parse


class UserLoginView(LoginView):
    template_name = 'admins/login.html'
    form_class = MyAuthForm

    def get_success_url(self):
        url = self.get_redirect_url()
        if url:
            return url
        if self.request.user.is_admin or self.request.user.is_moderator:
            return reverse('admins:admin_dashboard')
        if self.request.user.is_superuser:
            return f'/superuser/'
        else:
            return f'/'


def profile_detail(request, username):

    username = urllib.parse.unquote(username)

    profile = get_object_or_404(Profile, user__username=username)

    posts_list = Post.objects.filter(status='Approved', author=profile.user).order_by('-published_date')

    #follow
    following = profile.following.count()
    followers = Profile.objects.filter(following=profile.user).count()

    if request.user.is_authenticated:
        my_profile = Profile.objects.get(user=request.user)

        if profile.user in my_profile.following.all():
            follow = True
        else:
            follow = False

        context = {
            'profile':profile,
            'posts_list':posts_list,
            'following':following,
            'followers':followers,
            'follow':follow
            }

        template_name = 'profile/profile_detail.html'

        return render(request, template_name, context)


    context = {
        'profile':profile,
        'posts_list':posts_list,
        'following':following,
        'followers':followers,
    }

    template_name = 'profile/profile_detail.html'

    return render(request, template_name, context=context)

accounts/templates/profile/profile_detail.html
{% extends 'base.html' %}
{% load static %}
{% load comment_tags %}

{% block title %}{{profile.user.username}} profile{% endblock title %}

{% block stylesheet %}

<style>
    .card {
        box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
    }

    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 0 solid rgba(0,0,0,.125);
        border-radius: .25rem;
    }

    .card-body {
        flex: 1 1 auto;
        min-height: 1px;
        padding: 1rem;
    }

    .gutters-sm {
        margin-right: -8px;
        margin-left: -8px;
    }

    .gutters-sm>.col, .gutters-sm>[class*=col-] {
        padding-right: 8px;
        padding-left: 8px;
    }
    .mb-3, .my-3 {
        margin-bottom: 1rem!important;
    }
    .h-100 {
        height: 100%!important;
    }
    .shadow-none {
        box-shadow: none!important;
    }
</style>
{% endblock stylesheet %}

{% block content %}

<div class="container margin-top-120">
    <div class="main-body">
    
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                    <div class="d-flex flex-column align-items-center text-center">
                        <img src="{{profile.profile_picture.url}}" alt="Admin" class="rounded-circle" width="150" height="150">
                        <div class="mt-3">
                            <h4>{{profile.user.username}}</h4>
                            <div class="my-2 text-center">
                                <ul class="list-inline">
                                    <li class="list-inline-item"><i class="fa fa-users text-maroon" aria-hidden="true"></i></li>
                                    <li class="list-inline-item followers-count-{{profile.pk}}"><b>{{followers}}</b> followers</li>
                                    <li class="list-inline-item"><b>{% if following %}{{following}}{% else %}0{% endif %}</b> following</li>
                                </ul>
                            </div>
                            <p class="text-primary mb-1">{{profile.bio|safe}}</p>
                            <p class="text-muted fs-6"><i class="fa fa-map-marker me-2" aria-hidden="true"></i>{{profile.location}}</p>
                            {% if request.user.is_authenticated %}
                                {% if user.profile == profile %}
                                    <a href="{% url 'dashboard:profile_update' user.id %}" class="btn btn-secondary mx-3">Edit Profile</a>
                                {% else %}
                                <button id="follow-button" data-url="{% url 'posts:follow_profile' %}" profile_id="{{profile.pk}}" value="{{profile.pk}}" class="btn mx-3 {% if follow %}btn-success{% else %}btn-maroon{% endif %}">{% if follow %}Unfollow{% else %}Follow{% endif %}</button>
                                {% endif %}
                            {% else %}
                            <a class="btn btn-maroon mx-3" href="{% url 'account_login' %}?next={{request.path}}">Follow</a>
                            {% endif %}
                        </div>
                        <div class="mt-4 text-center">
                            <ul class="list-inline">
                                {% if profile.linkedin_link %}
                                <li class="list-inline-item"><a href="{{profile.linkedin_link}}" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a> </li>
                                {% endif %}
                                {% if profile.twitter_link %}
                                <li class="list-inline-item"><a href="{{profile.twitter_link}}" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a> </li>
                                {% endif %}
                                {% if profile.instagram_link %}
                                <li class="list-inline-item"><a href="{{profile.instagram_link}}" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                {% endif %}
                                {% if profile.facebook_link %}
                                <li class="list-inline-item"><a href="{{profile.facebook_link}}" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                {% endif %}
                                {% if profile.youtube_link %}
                                <li class="list-inline-item"><a href="{{profile.youtube_link}}" target="_blank"><i class="fa fa-youtube-play" aria-hidden="true"></i></a> </li>
                                {% endif %}
                                {% if profile.github_link %}
                                <li class="list-inline-item"><a href="{{profile.github_link}}" target="_blank"><i class="fa fa-github" aria-hidden="true"></i></a> </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
              </div>
            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <h3><b>All Activity</b></h3>
                        {% for post in posts_list %}
                        <a href="{% url 'main:post_detail' post.slug %}">
                            <div class="card mb-2 border-0 shadow-sm">
                                <div class="card-body">
                                    <h5 class="title card-title">{{post.title}}</h5>
                                    <ul class="list-inline">
                                        <li class="author list-inline-item">@{{post.author.username}}</li>
                                    </ul>
                                    
                                    <small class="py-3"> 
                                        {% for t in post.tags.all %}
                                        <a href="{% url 'posts:post_tag_list' t %}">
                                            <span class="badge bg-success">#{{t}}</span>
                                        </a>
                                        {% endfor %}
                                    </small>
                                    <div class="row mt-3">
                                    <div class="col-6">
                                        {% if request.user.is_authenticated %}
                                            {% if post.id in already_liked %}
                                                <a name="{{post.id}}" class="latest-likin" id="co" style="color: blue;"><i class="fa fa-thumbs-o-up me-2"></i></a><span class="me-3 likes-count-{{post.id}}">{{post.total_likes}}</span>
                                            {% else %}
                                                <a name="{{ post.id }}" style="color: black;" class="latest-likin" id="co"><i class="fa fa-thumbs-o-up me-2" aria-hidden="true"></i></a><span class="me-3 likes-count-{{post.id}}">{{post.total_likes}}</span>
                                            {% endif %}
                                        {% else %}
                                            <a name="{{ post.id }}" style="color: black;" class="latest-likin" href="{% url 'account_login' %}" id="co"><i class="fa fa-thumbs-o-up me-2" aria-hidden="true"></i></a><span class="me-3 likes-count-{{post.id}}">{{post.total_likes}}</span>
                                        {% endif %}


                                        <a><i class="fa fa-comments-o me-2"></i> {% get_comments_count post user %} </a>
                                    </div>
                                    <div class="col-6">
                                        <div class="d-flex d-flex justify-content-end">
                                            <small class="text-muted me-2">{{post.view_count}} <i class="fa fa-eye"></i></small>
                                            <small class="text-muted me-3">{{post.get_readtime}} read</small>
                                        </div>
                                    </div>
                                    </div>
                                
                                </div>                   
                            </div>
                        </a>
                        {% empty %}
                            <div class="text-center mb-5">
                                <img class="my-5" src="{% static 'images/no_item.svg' %}" height="150" width="auto" alt="no_item"><br>
                                <h6>Sorry, no Activity found!</h6>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
          </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
<script>
    $(document).ready(function() {
        $('#follow-button').click(function() {
            var url = $(this).attr('data-url');
            var profileID = $(this).attr('profile_id');
            var profile_pk = $(this).val();

            $.ajax({
                url:url,
                type: 'GET',
                data:{
                    'profile_pk':profile_pk
                },
                success: function (res) {
                    var _prevfollowers=$(".followers-count-"+profileID).text();

                    if (res.status == 'none') {
                        $("#follow-button").html("You can't follow yourself");
                        $("#follow-button").removeClass("btn-maroon");
                        $("#follow-button").removeClass("btn-success");
                        $("#follow-button").addClass("btn-warning");
                    }
                    else if (res.bool == true) {
                        $("#follow-button").html("Unfollow");
                        $("#follow-button").addClass("btn-success");
                        $("#follow-button").removeClass("btn-maroon");
                        $(".followers-count-"+profileID).text(parseInt(_prevfollowers)+1 + " followers");
                    }
                    else if(res.bool==false){
                        $("#follow-button").html("follow");
                        $("#follow-button").addClass("btn-maroon");
                        $("#follow-button").removeClass("btn-success");
                        $(".followers-count-"+profileID).text(parseInt(_prevfollowers)-1 + " followers");
                    }
                }
            })
        }); 
    });
</script>
{% endblock javascript %}