accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .import views

app_name = 'accounts'
 
urlpatterns = [
    path('admin-login/', views.UserLoginView.as_view(), name='admin_login'),

    path('admin_logout/', auth_views.LogoutView.as_view(), name='admin_logout'),

    path('change-password/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view() ,name='password_change_done'),

    path('profile/<str:username>/', views.profile_detail, name='profile_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from ckeditor_uploader.views import upload


urlpatterns = [
    path('superuser/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('allauth.urls')),
    path('account/', include('accounts.urls', namespace='account')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('marketing/', include('marketing.urls', namespace='marketing')),
    path('admin/', include('admins.urls', namespace='admins')),

    path('ckeditor/upload/', login_required(upload), name='ckeditor_upload'),
    
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('comment/', include('comment.urls')),
    path('books/', include('books.urls', namespace='books')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from .import views

app_name = 'dashboard'

urlpatterns = [
   path('posts/', views.dashboard, name='dashboard'),
   path('profile/<int:id>/edit/', views.profile_update, name='profile_update'),
   path('reading-list/', views.reading_list, name='reading_list'),
   path('followers/', views.followers, name='followers'),
   path('following/', views.following, name='following'),
]

main/urls.py
from django.urls import path

from .import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('yesterday/posts/', views.yesterday_posts, name='yesterday_posts'),
    path('weekly/posts/', views.weekly_posts, name='week-post'),
    path('monthly/posts/', views.monthly_posts, name='month-post'),
    path('yearly/posts/', views.yearly_posts, name='year-post'),
    path('<slug:post_slug>/', views.post_detail, name='post_detail'),

    path('pages/code-of-conducts/', views.code_of_conduct, name='code_of_conduct'),
    path('pages/terms-of-use/', views.terms_of_use, name='terms_of_use'),
    path('pages/privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('pages/contacts/', views.contacts, name='contacts'),
    path('pages/about/', views.about, name='about'),
    path('pages/faq/', views.FAQ, name='faq'),
   
]

posts/urls.py
from django.urls import path

from .import views

app_name = 'posts'

urlpatterns = [
    path('write-post/', views.create_edit_post, name='create_post'),
    path('<int:id>/edit/', views.create_edit_post, name="edit_post"),
    path('<int:id>/delete/', views.delete_post, name='delete_post'),
    path('save-post-bookmark/', views.save_post_bookmark, name='save_post_bookmark'),
    path('follow/', views.follow_profile, name='follow_profile'),
    path('search/', views.search, name='search'),
    path('tags/<str:tag>/', views.post_tag_list, name='post_tag_list'),

    path('save_likes/', views.save_likes, name='save_likes'),

    path('ajax-authenticate-user/', views.ajax_authenticate_user, name='ajax_authenticate_user'),
]

comment/models/followers.py
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.db import models

from comment.managers.followers import FollowerManager


class Follower(models.Model):
    email = models.EmailField()
    username = models.CharField(max_length=50)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    objects = FollowerManager()

    def __str__(self):
        return f'{str(self.content_object)} followed by {self.email}'

    def __repr__(self):
        return self.__str__()

dashboard/forms.py
from django import forms

from accounts.models import Profile

class ProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, \
     error_messages ={'invalid':("Image files only")},\
     widget=forms.FileInput)


    class Meta:
        model = Profile
        fields = ['profile_picture','website', 'country', 'location', 'display_email', 'bio', 'youtube_link', 'facebook_link', 'instagram_link', 'linkedin_link','twitter_link','github_link',]
        widgets = {
			'bio': forms.Textarea(attrs={'rows': 3}),
		}

comment/views/followers.py
from django.views.generic.base import View

from comment.models import Follower
from comment.mixins import CanSubscribeMixin, DABResponseData
from comment.responses import UTF8JsonResponse
from comment.validators import ContentTypeValidator, DABEmailValidator
from comment.messages import FollowError


class BaseToggleFollowView(ContentTypeValidator, DABResponseData):
    response_class = None

    def get_response_class(self):
        assert self.response_class is not None, (
                "'%s' should either include a `response_class` attribute, "
                "or override the `get_response_class()` method."
                % self.__class__.__name__
        )
        return self.response_class

    def post(self, request, *args, **kwargs):
        """ Allow authenticated users only, anonymous may be added in the future """
        email = request.POST.get('email', None)
        response_class = self.get_response_class()
        if email and not DABEmailValidator(email).is_valid():
            self.error = {
                'invalid_email': DABEmailValidator.message
            }
            self.status = 400
            return response_class(self.json(), status=self.status)

        user = request.user
        if user.email:
            email = user.email

        if not email:
            self.error = {
                'email_required': FollowError.EMAIL_REQUIRED.format(model_object=str(self.model_obj))
            }
            self.status = 400
            return response_class(self.json(), status=self.status)

        if not user.email:
            user.email = email
            user.save()

        username = user.username or email.aplit('@')[0]
        following = Follower.objects.toggle_follow(email=email, model_object=self.model_obj, username=username)
        self.data = {
            'following': following,
            'app_name': self.model_obj._meta.app_label,
            'model_name': self.model_obj.__class__.__name__,
            'model_id': self.model_obj.id,
            'model_object': str(self.model_obj)
        }
        return response_class(self.json())


class ToggleFollowView(BaseToggleFollowView, CanSubscribeMixin, View):
    response_class = UTF8JsonResponse

dashboard/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.db.models import Sum
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required

from posts.models import Post, PostBookmark
from accounts.models import Profile
from .forms import ProfileForm


@login_required
def dashboard(request):
    user = request.user
    posts = Post.objects.filter(author=user).order_by('-created_at')
    post_views = posts.aggregate(total=Sum('view_count'))
    profile = Profile.objects.get(user=user)
    following = profile.following.count()

    followers = Profile.objects.filter(following=profile.user).count()

    context = {
        'posts':posts,
        'post_views':post_views,
        'total_post':posts.count(),
        'following':following,
        'followers':followers,
    }

    template_name = 'dashboard/index.html'

    return render(request, template_name, context)

@login_required
def profile_update(request, id):

    profile = get_object_or_404(Profile, user_id=id)

    if profile.user != request.user: 
        raise PermissionDenied()

    form = ProfileForm(request.POST or None, request.FILES or None, instance=profile)

    if form.is_valid():
        form.save()

        return redirect(reverse("accounts:profile_detail", kwargs={
            'username': request.user.username
        }))
        messages.success(request, "You are successfully update profile")
    else:
        form = ProfileForm(instance=profile)

    context = {
        'form':form
    }

    template_name = 'dashboard/profile_update.html'

    return render(request, template_name, context)


@login_required
def reading_list(request):

    user = request.user
    
    posts = PostBookmark.objects.filter(user=user).order_by('-created_at')

    context = {'posts':posts}
    
    template_name = 'dashboard/reading_list.html'

    return render(request, template_name, context)

def followers(request):

    
    profile = get_object_or_404(Profile, pk=request.user.profile.pk)

    followers = Profile.objects.filter(following=profile.user)

    context ={
        'followers':followers
    }

    template_name = 'dashboard/followers.html'

    return render(request, template_name, context)

def following(request):

    profile = get_object_or_404(Profile, pk=request.user.profile.pk)

    following = profile.following.all()
    print(following)

    context ={
        'following':following
    }

    template_name = 'dashboard/following.html'

    return render(request, template_name, context)

dashboard/templates/dashboard/followers.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Followers {% endblock title %}

{% block stylesheet %}
{% endblock stylesheet %} 

{% block content %}

<div class="container margin-top-80 pt-5 margin-bottom-60" style="min-height: 100vh;">

    <div class="row">
        <div class="col-lg-3 nav-pills">
            {% include 'dashboard/includes/sidebar.html' %}
        </div>
        <div class="col-lg-9">
            {% include 'dashboard/includes/mobile_sidebar.html' %}
            <div class="card border-0 shadow-sm">
                <div class="card-body">
                    <div class="pb-3">
                        <h4><strong>Followers ({{followers.count}})</strong></h4>
                    </div>

                    <div class="row">
                        {% for follower in followers %}
                        <div class="col-lg-3 col-sm-6">
                            <div class="card border-0 shadow-sm">
                                <a href="{% url 'accounts:profile_detail' follower.user.username %}">
                                    <div class="card-body">
                                        <div class="text-center">
                                            <img src="{{follower.profile_picture.url}}" class="rounded-circle" width="100" height="100" alt="profile-image">
                                        </div>
                                        <p class="my-3 text-primary text-center"><b>@{{follower.user.username}}</b></p>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% empty %}
                        <div class="text-center">
                            <img src="{% static 'images/no_item.svg' %}" height="100" width="auto" alt="no_item"><br>
                            <a class="btn btn-primary my-3">Save a Post for Future Reading</a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

dashboard/templates/dashboard/following.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Following users {% endblock title %}

{% block stylesheet %}
{% endblock stylesheet %} 

{% block content %}

<div class="container margin-top-80 pt-5 margin-bottom-60" style="min-height: 100vh;">

    <div class="row">
        <div class="col-lg-3 nav-pills">
            {% include 'dashboard/includes/sidebar.html' %}
        </div>
        <div class="col-lg-9">
            {% include 'dashboard/includes/mobile_sidebar.html' %}
            <div class="card border-0 shadow-sm">
                <div class="card-body">
                    <div class="pb-3">
                        <h4><strong>Following users ({{following.count}})</strong></h4>
                    </div>

                    <div class="row">
                        {% for follow in following %}
                        <div class="col-lg-3 col-sm-6">
                            <div class="card border-0 shadow-sm">
                                <a href="{% url 'accounts:profile_detail' follow %}">
                                    <div class="card-body">
                                        <div class="text-center">
                                            <img src="{{follow.profile.profile_picture.url}}" class="rounded-circle" width="100" height="100" alt="profile-image">
                                        </div>
                                        <p class="my-3 text-primary text-center"><b>@{{follow}}</b></p>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% empty %}
                        <div class="text-center">
                            <img src="{% static 'images/no_item.svg' %}" height="100" width="auto" alt="no_item"><br>
                            <a class="btn btn-primary my-3">Save a Post for Future Reading</a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'base.html' %}
{% load active_link_tags %}
{% load static %}

{% block title %} {{user.username}} - Posts{% endblock title %}


{% block content %}

    <div class="container margin-top-80 pt-3 margin-bottom-60" style="min-height: 100vh;">
        <div class="row pb-2">
            <div class="col-6"><h2><Strong>Dashboard</Strong></h2></div>
            <div class="col-6 d-flex justify-content-end">
               {% include 'dashboard/includes/mobile_sidebar.html' %}
            </div>
        </div>
        <div class="row pb-5 h-100 g-3">
            <div class="col-lg-3">
                <div class="card border-0 shadow-sm p-2">
                    <div class="card-body">
                        <h3><strong>{{total_post}}</strong></h3>
                        <p>Total Posts</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="card border-0 shadow-sm p-2">
                    <div class="card-body">
                        <h3><strong>
                            {% if post_views.total %}
                            {{post_views.total}}
                            {% else %} 0 {% endif %}
                        </strong></h3>
                        <p>Total Posts Views</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="card border-0 shadow-sm p-2">
                    <a href="{% url 'dashboard:followers' %}">
                        <div class="card-body">
                            <h3><strong>{{followers}}</strong></h3>
                            <p>Followers</p>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="card border-0 shadow-sm p-2">
                    <a href="{% url 'dashboard:following' %}">
                        <div class="card-body">
                            <h3><strong>{{following}}</strong></h3>
                            <p>Following</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 nav-pills">
                {% include 'dashboard/includes/sidebar.html' %}
            </div>
            <div class="col-lg-9">
                <div class="card border-0 shadow-sm">
                    <div class="card-body">
                        <div class="pb-3">
                            <h4><strong>Posts</strong></h4>
                        </div>
                        <div>
                            <table class="table table-borderless">
                                <tbody>
                                    {% for post in posts %}
                                    <tr>
                                        <td>{{forloop.counter}}.</td>
                                        <td>
                                            <a class="text-primary" href="{% url 'main:post_detail' post.slug %}"><strong>{{post.title}}</strong></a>
                                        </td>
                                        <td><i class="me-2 fa fa-eye"></i>{{post.view_count}}</td>
                                        <td>
                                            <span class="badge {% if post.status == 'Pending' %}bg-warning{% else %}bg-success{% endif %}">{{post.status}}</span>
                                        </td>
                                        <td>
                                            <a class="text-primary" href="{% url 'posts:edit_post' post.id %}"><i class="fa fa-edit me-2"></i></a>
                                            <a class="text-danger confirm-delete" href="{% url 'posts:delete_post' post.id %}"><i class="fa fa-times-circle"></i></a>
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <div class="text-center">
                                        <img src="{% static 'images/no_item.svg' %}" height="100" width="auto" alt="no_item"><br>
                                        <a class="btn btn-primary my-3" href="{% url 'posts:create_post' %}">Write a post</a>
                                    </div>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}


{% block javascript %}

<script>
    $(document).on('click', '.confirm-delete', function(){
        return confirm('Are you sure you want to delete this?');
    });
</script>
{% endblock javascript %}

dashboard/templates/dashboard/profile_update.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %} Update {{user.username}} Profile {% endblock title %}

{% block stylesheet %}
    <style>
        .card .image-circle{
            width: 80px;
            height: 80px;
            border: 1px solid rgb(197, 181, 181);
        }
    </style>
{% endblock stylesheet %}

{% block content %}
<div class="container margin-top-80 pt-3 margin-bottom-60" style="min-height: 100vh;">
    <div class="row">
        <div class="col-lg-3 nav-pills">
            {% include 'dashboard/includes/sidebar.html' %}
        </div>
        <div class="col-lg-9">
            {% include 'dashboard/includes/mobile_sidebar.html' %}
            <div class="card border-0 shadow-sm">
                <div class="card-body">
                    <div class="pb-3">
                        <h4><strong><span class="text-primary">{{user.username}}'s</span> Profile</strong></h4>
                    </div>
                    <div>
                        <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
                            
                            <div class="row">
                                <div class="col-lg-2 text-center">
                                    <img class="image-circle rounded-circle" src="{{user.profile.profile_picture.url}}" alt="profile">
                                </div>
                                <div class="col-lg-10">
                                    <label for=""><b>Profile Picture</b></label>
                                    {% render_field form.profile_picture class="form-control mt-2" placeholder="" %}
                                </div>
                            </div>
                            <div class="mb-3 mt-4">
                                <label class="mb-2 me-4" for=""><b>Bio</b></label>
                                {% render_field form.bio class="form-control" placeholder="Write a short bio......" %}
                            </div>
                            <div class="mb-3">
                                <label class="mb-2" for=""><b>Website</b></label>
                                {% render_field form.website class="form-control" placeholder="" %}
                            </div>
                            <div class="mb-3">
                                <label class="mb-2" for=""><b>Country</b></label>
                                {% render_field form.country class="form-control" placeholder="" %}
                            </div>
                            <div class="mb-3">
                                <label class="mb-2" for=""><b>Location</b></label>
                                {% render_field form.location class="form-control" placeholder="" %}
                            </div>
                            <div class="mb-3">
                                <label class="mb-2 me-4" for=""><b>Do you agree your email to be desplayed on your public profile?</b></label>
                                {% render_field form.display_email class="radio" placeholder="" %}
                            </div>
                            
                            <div class="mb-3">
                                <label class="mb-2 me-4" for=""><b>Youtube Link</b></label>
                                {% render_field form.youtube_link class="form-control" placeholder="" %}
                            </div>
                            <div class="mb-3">
                                <label class="mb-2 me-4" for=""><b>Facebook Link</b></label>
                                {% render_field form.facebook_link class="form-control" placeholder="" %}
                            </div>
                            <div class="mb-3">
                                <label class="mb-2 me-4" for=""><b>Instagram Link</b></label>
                                {% render_field form.instagram_link class="form-control" placeholder="" %}
                            </div>
                            <div class="mb-3">
                                <label class="mb-2 me-4" for=""><b>Linkedin Link</b></label>
                                {% render_field form.linkedin_link class="form-control" placeholder="" %}
                            </div>
                            <div class="mb-3">
                                <label class="mb-2 me-4" for=""><b>Twitter Link</b></label>
                                {% render_field form.twitter_link class="form-control" placeholder="" %}
                            </div>
                            <div class="mb-3">
                                <label class="mb-2 me-4" for=""><b>Github Link</b></label>
                                {% render_field form.github_link class="form-control" placeholder="" %}
                            </div>

                            <div class="d-grid gap-2 col-8 mx-auto py-4">
                                <button class="btn btn-maroon py-2" type="submit">Save Profile</button>
                            </div>
                            
                            
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}{% endblock javascript %}

dashboard/templates/dashboard/reading_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Reading Lists {% endblock title %}

{% block content %}

<div class="container margin-top-80 pt-5 margin-bottom-60" style="min-height: 100vh;">

    <div class="row">
        <div class="col-lg-3 nav-pills">
            {% include 'dashboard/includes/sidebar.html' %}
        </div>
        <div class="col-lg-9">
            {% include 'dashboard/includes/mobile_sidebar.html' %}
            <div class="card border-0 shadow-sm">
                <div class="card-body">
                    <div class="pb-3">
                        <h4><strong>Reading Posts</strong></h4>
                    </div>
                    <div>
                        <table class="table table-borderless">
                            <tbody>
                                {% for post in posts %}
                                <tr>
                                    <td>{{forloop.counter}}.</td>
                                    <td>
                                        <a class="text-primary" href="{% url 'main:post_detail' post.post.slug %}"><strong>{{post.post.title}}</strong></a>
                                    </td>
                                </tr>
                                {% empty %}
                                <div class="text-center">
                                    <img src="{% static 'images/no_item.svg' %}" height="100" width="auto" alt="no_item"><br>
                                    <a class="btn btn-primary my-3">Sorry No Reading list</a>
                                </div>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}