books/urls.py
from django.urls import path

from books.views import (
    books
)

app_name = 'books'

urlpatterns = [
    path('home/', books.home, name='home'),
    path('details/<str:slug>/', books.book_details, name='book_detail'),
    path('download/<str:slug>/', books.download_book, name='download_book'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from ckeditor_uploader.views import upload


urlpatterns = [
    path('superuser/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('allauth.urls')),
    path('account/', include('accounts.urls', namespace='account')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('marketing/', include('marketing.urls', namespace='marketing')),
    path('admin/', include('admins.urls', namespace='admins')),

    path('ckeditor/upload/', login_required(upload), name='ckeditor_upload'),
    
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('comment/', include('comment.urls')),
    path('books/', include('books.urls', namespace='books')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('yesterday/posts/', views.yesterday_posts, name='yesterday_posts'),
    path('weekly/posts/', views.weekly_posts, name='week-post'),
    path('monthly/posts/', views.monthly_posts, name='month-post'),
    path('yearly/posts/', views.yearly_posts, name='year-post'),
    path('<slug:post_slug>/', views.post_detail, name='post_detail'),

    path('pages/code-of-conducts/', views.code_of_conduct, name='code_of_conduct'),
    path('pages/terms-of-use/', views.terms_of_use, name='terms_of_use'),
    path('pages/privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('pages/contacts/', views.contacts, name='contacts'),
    path('pages/about/', views.about, name='about'),
    path('pages/faq/', views.FAQ, name='faq'),
   
]

books/models.py
import uuid
import os
from uuid import uuid4
from django.utils import timezone
from datetime import datetime
from django.utils.text import slugify
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator


User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Book(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    title = models.CharField(max_length=250)
    slug = models.SlugField(default='', max_length=250, editable=False, unique=True)
    author = models.CharField(max_length=100)
    description = models.TextField()
    published = models.CharField(max_length=50)
    pages = models.PositiveIntegerField(default=1)
    downloads = models.PositiveIntegerField(default=0)
    thumbnail = models.ImageField(upload_to='books/thumbnails/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    file = models.FileField(upload_to='books/all-books/', validators=[FileExtensionValidator(allowed_extensions=['pdf'])])

    def __str__(self):
        return self.title

    @property
    def filename(self):
        return os.path.basename(self.file.name)

    def save(self, *args, **kwargs):
        super(Book, self).save(*args, **kwargs)

        if not self.slug:
            random_code = datetime.now().strftime('%H%M%S')
            self.slug = str(random_code) + "-" + slugify(self.title)
        return super().save(*args, **kwargs)

books/views/books.py
import os
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required

from books.models import Book, Category

def home(request):
    books = Book.objects.all().order_by('-created_at')
    categories = Category.objects.all().order_by('id')[:24]
    context = {
        'categories':categories,
        'books':books
    }
    template_name = 'books/index.html'
    return render(request, template_name, context)


@login_required
def book_details(request, slug):

    book = get_object_or_404(Book, slug=slug)

    context = {
        'book':book
    }
    template_name = 'books/book_detail.html'
    return render(request, template_name, context)


@login_required
def download_book(request, slug):
    book = get_object_or_404(Book, slug=slug)
    filename =  os.path.basename(book.file.name)
    file = book.file
    if file:
        response = HttpResponse(file, content_type='application/pdf')
        download = request.POST.get("download")
        content = "filename=%s" %(filename)
        if download:
            book.downloads += 1
            book.save()
            content = content
        response['Content-Disposition'] = content
        return response
    return HttpResponse("Not found")

books/templates/books/base.html
<!DOCTYPE html>
{% load static %}
{% load google_analytics %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="The platform help people to upscale their skills and knowledge in Agriculture, Financial and Information Technology (IT)">
    <meta name="keywords" content="agriculture,financial,information technology, coding, django, python, java, php, html, javascript, laravel, bootstrap, jquery, greenhouse, maize, tomato, rice, drip irrigation">
    <meta name="author" content="Technology Homesite">
    <meta name="generator" content="Sogea 1.0.0">

    <title>{% block title %}{% endblock title %} | Sogea Community</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

     <!-- custom css -->
    <link rel="stylesheet" href="{% static 'books/css/style.css' %}">
    
    <!-- fontawesome icons -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.ico' %}">
    <link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'images/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    {% google_analytics %}
    {% block stylesheet %} {% endblock stylesheet %}
</head>

<body class="bg-site">
    {% include 'books/includes/header.html' %}

    
    {% block content %}{% endblock %}
  
    

    {% include 'books/includes/footer.html' %}
    {% include 'books/includes/scripts.html' %}

    {% block javascript %} {% endblock javascript %}
</body> 
</html>

books/templates/books/book_detail.html
{% extends 'books/base.html' %}
{% load static %}

{% block title %} Books-Name {% endblock title %} 

{% block stylesheet %} {% endblock stylesheet %} 

{% block content %} 
  <!-- Popular Free Books -->
  <div class="container book margin-top-120 margin-bottom-60" style="min-height: 100vh;">
    <div class="row g-3">
        <div class="col-md-2">
            <div class="card shadow-sm mb-3">
                <img src="{{book.thumbnail.url}}"
                  class="card-img-top" alt=""/>
            </div>
            <div>PUBLISHED: {{book.published}}</div>
            <div>PAGES: {{book.pages}}</div>
            <div>DOWNLOADS: {{book.downloads}}</div>
        </div>
        <div class="col-md-10">
            <h2>{{book.title|capfirst}}</h2>
            <a href=""><b>By {{book.author}}</b></a>

            <form method="POST" action="{% url 'books:download_book' book.slug %}">
                {% csrf_token %}
                <input type="hidden" name="download" value="1">
                <div class="my-3">
                    <button type="submit" class="btn btn-maroon px-5 py-3"><i class="fa fa-download me-2"></i><b>Free Download</b></button>
                </div>
            </form>

            <div class="alert alert-dark">
                <small>This book is available for free download in a pdf formats only, You can also read the full text online using our ereader.</small>
            </div>

            <div class="my-3">
                <p>{{book.description|safe}}</p>
            </div>
        </div>
    </div>
  </div>
{% endblock %} 

{% block javascript %} {% endblock javascript %}

books/templates/books/index.html
{% extends 'books/base.html' %}
{% load static %}

{% block title %} Books {% endblock title %} 

{% block stylesheet %}
<style>
  .banner h2{
    color: white;
    font-size: 40px;
    font-weight: 700;
  }
  .banner p{
    color: white;
    font-size: 20px
  }
</style>
{% endblock stylesheet %} 

{% block content %} 
  <!-- Background image -->
  <div class="p-5 banner">
    <div class="mask">
      <div class="container margin-top-120">
        <div class="row">
          <div class="col-md-12">
            <h2>Join to access our best free & discounted ebooks.</h2>
            <p>We find the best ebook deals so you don't have to. Never pay full price again.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Background image -->

  <!-- Books Category -->
  <div class="container books-category margin-top-60 margin-bottom-60">
    <div class="row">
      <h4>BROWSE CATEGORY <a href="#">(view All)</a></h4>
    </div>
    <div class="row">
      {% for category in categories %}
      <div class="col-lg-3 col-md-4 col-6">
        <a href="#">{{category.name}} <span>({{category.book_set.all.count}})</span></a>
      </div>
      {% endfor %}
    </div>
  </div>

  <!-- Popular Free Books -->
  <div class="container books-category margin-top-60 margin-bottom-60">
    <div class="row">
      <h4>FREE EBOOKS</h4>
    </div>
    <div class="row g-3">
      {% for book in books %}
      <div class="col-lg-2 col-md-4 col-6">
        <a href="{% url 'books:book_detail' book.slug %}">
          <div class="card shadow-sm">
            <img src="{{book.thumbnail.url}}"
              class="card-img-top" alt=""/>
          </div>
        </a>
        <a class="book-title" href="{% url 'books:book_detail' book.slug %}">{{book.title|capfirst}}</a>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %} 

{% block javascript %} {% endblock javascript %}