config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from ckeditor_uploader.views import upload


urlpatterns = [
    path('superuser/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('allauth.urls')),
    path('account/', include('accounts.urls', namespace='account')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('marketing/', include('marketing.urls', namespace='marketing')),
    path('admin/', include('admins.urls', namespace='admins')),

    path('ckeditor/upload/', login_required(upload), name='ckeditor_upload'),
    
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('comment/', include('comment.urls')),
    path('books/', include('books.urls', namespace='books')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('yesterday/posts/', views.yesterday_posts, name='yesterday_posts'),
    path('weekly/posts/', views.weekly_posts, name='week-post'),
    path('monthly/posts/', views.monthly_posts, name='month-post'),
    path('yearly/posts/', views.yearly_posts, name='year-post'),
    path('<slug:post_slug>/', views.post_detail, name='post_detail'),

    path('pages/code-of-conducts/', views.code_of_conduct, name='code_of_conduct'),
    path('pages/terms-of-use/', views.terms_of_use, name='terms_of_use'),
    path('pages/privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('pages/contacts/', views.contacts, name='contacts'),
    path('pages/about/', views.about, name='about'),
    path('pages/faq/', views.FAQ, name='faq'),
   
]

marketing/urls.py
from django.urls import path

from .import views

app_name = 'marketing'

urlpatterns = [
    path('email-signup/', views.email_list_signup, name='email-list-signup'),
]

posts/urls.py
from django.urls import path

from .import views

app_name = 'posts'

urlpatterns = [
    path('write-post/', views.create_edit_post, name='create_post'),
    path('<int:id>/edit/', views.create_edit_post, name="edit_post"),
    path('<int:id>/delete/', views.delete_post, name='delete_post'),
    path('save-post-bookmark/', views.save_post_bookmark, name='save_post_bookmark'),
    path('follow/', views.follow_profile, name='follow_profile'),
    path('search/', views.search, name='search'),
    path('tags/<str:tag>/', views.post_tag_list, name='post_tag_list'),

    path('save_likes/', views.save_likes, name='save_likes'),

    path('ajax-authenticate-user/', views.ajax_authenticate_user, name='ajax_authenticate_user'),
]

main/views.py
from django.shortcuts import render, get_object_or_404, Http404, redirect
from django.core.exceptions import ObjectDoesNotExist
import json
from django.http import HttpResponse
from datetime import datetime, timedelta

from posts.models import Post,PostBookmark
from accounts.models import Profile
from marketing.forms import EmailSignupForm


def homepage(request):

    template_name = 'main/index.html'

    posts_list = Post.objects.filter(status='Approved').exclude(featured=True).order_by('-published_date')

    try:
        p_ft = Post.objects.get(featured=True)
        common_tags = Post.tags.most_common()[:4]
    except Post.DoesNotExist:
        p_ft = None
        common_tags = None

   
    context = {
        'posts_list':posts_list,
        'form':EmailSignupForm(),
        'common_tags':common_tags,
        'p_ft':p_ft,
    }

    return render(request, template_name, context=context)


def yesterday_posts(request):

    template_name = 'main/index.html'

    one_day_ago = datetime.today() - timedelta(days=1)

    print(one_day_ago)

    posts_list = Post.objects.filter(published_date__lte=one_day_ago, status='Approved').exclude(featured=True).order_by('-published_date')

    print('posts_list:',posts_list)

    try:
        p_ft = Post.objects.get(featured=True)
        common_tags = Post.tags.most_common()[:4]
    except Post.DoesNotExist:
        p_ft = None
        common_tags = None

    context = {
        'posts_list':posts_list,
        'form':EmailSignupForm(),
        'common_tags':common_tags,
        'p_ft':p_ft,
    }

    return render(request, template_name, context=context)


def weekly_posts(request):

    template_name = 'main/index.html'

    one_week_ago = datetime.today() - timedelta(days=7)

    posts_list = Post.objects.filter(published_date__lte=one_week_ago, status='Approved').exclude(featured=True).order_by('-published_date')

    try:
        p_ft = Post.objects.get(featured=True)
        common_tags = Post.tags.most_common()[:4]
    except Post.DoesNotExist:
        p_ft = None
        common_tags = None

    context = {
        'posts_list':posts_list,
        'form':EmailSignupForm(),
        'common_tags':common_tags,
        'p_ft':p_ft,
    }

    return render(request, template_name, context=context)


def monthly_posts(request):

    template_name = 'main/index.html'

    one_month_ago = datetime.today() - timedelta(days=30)

    posts_list = Post.objects.filter(published_date__lte=one_month_ago, status='Approved').exclude(featured=True).order_by('-published_date')
   
    try:
        p_ft = Post.objects.get(featured=True)
        common_tags = Post.tags.most_common()[:4]
    except Post.DoesNotExist:
        p_ft = None
        common_tags = None

    context = {
        'posts_list':posts_list,
        'form':EmailSignupForm(),
        'common_tags':common_tags,
        'p_ft':p_ft,
    }

    return render(request, template_name, context=context)


def yearly_posts(request):

    template_name = 'main/index.html'

    one_year_ago = datetime.today() - timedelta(days=365)

    posts_list = Post.objects.filter(published_date__lte=one_year_ago, status='Approved').exclude(featured=True).order_by('-published_date')
   
    try:
        p_ft = Post.objects.get(featured=True)
        common_tags = Post.tags.most_common()[:4]
    except Post.DoesNotExist:
        p_ft = None
        common_tags = None

    context = {
        'posts_list':posts_list,
        'form':EmailSignupForm(),
        'common_tags':common_tags,
        'p_ft':p_ft,
    }

    return render(request, template_name, context=context)


def post_detail(request, post_slug):

    post = get_object_or_404(Post, slug=post_slug)

    if not request.user == post.author:
        post.view_count += 1
        post.save()

    post_bookmarks = PostBookmark.objects.filter(post=post).count()

    if request.user.is_authenticated:
        post_state = PostBookmark.objects.filter(user=request.user, post=post)
        like_state = post.likes.filter(id=request.user.id)


        following = post.author.profile.following.count()
        followers = Profile.objects.filter(following=post.author).count()

        #follow
  
        view_profile = Profile.objects.get(pk=post.author.profile.pk)
 
        my_profile = Profile.objects.get(user=request.user)
  

        if view_profile.user in my_profile.following.all():
            follow = True
        else:
            follow = False

        context = {
            'followers':followers,
            'following':following,
            'post_state':post_state,
            'like_state':like_state, 
            'follow':follow, 
            'profile':my_profile,
            'post':post,
            'post_bookmarks':post_bookmarks,
        }

        template_name = 'main/post_detail.html'

        return render(request, template_name, context)

    context = {
        'post':post,
        'post_bookmarks':post_bookmarks,
    }

    template_name = 'main/post_detail.html'

    return render(request, template_name, context)


def code_of_conduct(request):

    context = {}
    template_name = 'main/pages/code_of_conduct.html'
    return render(request, template_name, context)

def terms_of_use(request):

    context = {}
    template_name = 'main/pages/terms_of_use.html'
    return render(request, template_name, context)

def privacy_policy(request):

    context = {}
    template_name = 'main/pages/privacy_policy.html'
    return render(request, template_name, context)

def contacts(request):

    context = {}
    template_name = 'main/pages/contacts.html'
    return render(request, template_name, context)

def about(request):

    context = {}
    template_name = 'main/pages/about.html'
    return render(request, template_name, context)

def FAQ(request):

    context = {}
    template_name = 'main/pages/faq.html'
    return render(request, template_name, context)

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% load socialaccount %}
{% load widget_tweaks %}
{% load active_link_tags %}
{% load comment_tags %}

{% block title %}All Feeds{% endblock title %}

{% block stylesheet %}
    <style>
        .card:active{
            border: 2px solid maroon;
        }
        .card{
            cursor: pointer;
        }
        .card .title {
            font-size: 24px;
            font-weight:700;
        }

        .card .title:hover{
            color: maroon;
            cursor: pointer;
        }
        .card .image-circle{
            width: 30px;
            height: 30px;
            border: 1px solid rgb(197, 181, 181);
        }
        .card a:hover{
            color: maroon;
        }
        .author {
            font-size: 13px;
        }
        .card i{
            cursor: pointer;
        }
        .card-img-top {
            width: 100%;
            height: 330px;
            object-fit: cover;
        }
        .active{
            color:blue;
            font-weight: 600;
        }
    </style>
{% endblock stylesheet %}

{% block content %}
<main>
    <div class="position-relative overflow-hidden padding-top-80">
        <div class="row">
            <div class="col-lg-2 pt-3 pb-5 d-none d-lg-block">
                {% include 'main/includes/sidebar.html' %}
                
            </div>
            <div class="col-lg-7 mt-3">
                <div class="row">
                    <div class="col-3">
                        <h5><b>Posts</b></h5>
                    </div>
                    <div class="col-9 d-flex justify-content-end">
                        <ul class="list-inline">
                            <li class="list-inline-item"><a class="{% active_link 'main:homepage' 'active' strict=True %}" href="{% url 'main:homepage' %}">All</a></li>
                            <li class="list-inline-item"><a class="{% active_link 'main:yesterday_posts' 'active' strict=True %}" href="{% url 'main:yesterday_posts' %}">Yesterday</a></li>
                            <li class="list-inline-item"><a class="{% active_link 'main:week-post' 'active' strict=True %}" href="{% url 'main:week-post'  %}">Week</a></li>
                            <li class="list-inline-item"><a class="{% active_link 'main:month-post' 'active' strict=True %}" href="{% url 'main:month-post' %}">Month</a></li>                           
                        </ul>
                    </div>
                </div>

                {% if p_ft %}
                    <a href="{% url 'main:post_detail' p_ft.slug %}">
                    <div class="card mb-3 border-0 shadow-sm">
                        
                        <img src="{{p_ft.featured_image.url}}" class="card-img-top d-none d-lg-block" width="100%" height="auto" alt="{{p_ft.title}}">
                        <img src="{{p_ft.featured_image.url}}" class="d-lg-none" width="100%" height="auto" alt="{{p_ft.title}}">

                        <div class="card-body">
                            <h5 class="title card-title">{{p_ft.title}}</h5>
                            <ul class="list-inline">
                                <li class="list-inline-item"><img class="image-circle rounded-circle"src="{{p_ft.author.profile.profile_picture.url}}" alt="{{p_ft.title}}"></li>
                                <li class="author list-inline-item">@{{p_ft.author.username}}</li>
                            </ul>
                            
                            <small class="py-3"> 
                                {% for mt in p_ft.tags.all %}
                                <a href="{% url 'posts:post_tag_list' mt %}">
                                    <span class="badge bg-success">#{{mt}}</span>
                                </a>
                                {% endfor %}
                            </small>
                            <div class="row mt-3">
                            <div class="col-6">
                                {% if request.user.is_authenticated %}
                                    {% if p_ft.id in already_liked %}
                                        <a name="{{p_ft.id}}" class="likin" id="co" style="color: blue;"><i class="fa fa-thumbs-o-up me-2"></i></a><span class="me-3 like-count-{{p_ft.id}}">{{p_ft.total_likes}}</span>
                                    {% else %}
                                        <a name="{{ p_ft.id }}" style="color: black;" class="likin" id="co"><i class="fa fa-thumbs-o-up me-2" aria-hidden="true"></i></a><span class="me-3 like-count-{{p_ft.id}}">{{p_ft.total_likes}}</span>
                                    {% endif %}
                                {% else %}
                                    <a name="{{ p_ft.id }}" style="color: black;" class="likin" href="{% url 'account_login' %}" id="co"><i class="fa fa-thumbs-o-up me-2" aria-hidden="true"></i></a><span class="me-3 like-count-{{p_ft.id}}">{{p_ft.total_likes}}</span>
                                {% endif %} 

                                <a><i class="fa fa-comments-o me-2"></i> {% get_comments_count p_ft user %}</a>
                            </div>
                            <div class="col-6">
                                <div class="d-flex d-flex justify-content-end">
                                    <small class="text-muted me-2">{{p_ft.view_count}} <i class="fa fa-eye"></i></small>
                                    <small class="text-muted me-3">{{p_ft.get_readtime}} read</small>
                                </div>
                            </div>
                            </div>
                        
                        </div>
                    </div>
                    </a>
                {% endif %}
               

                {% for post in posts_list %}
                <a href="{% url 'main:post_detail' post.slug %}">
                    <div class="card mb-2 border-0 shadow-sm">
                        <div class="card-body">
                            <h5 class="title card-title">{{post.title}}</h5>
                            <ul class="list-inline">
                                <li class="list-inline-item"><img class="image-circle rounded-circle"src="{{post.author.profile.profile_picture.url}}" alt="{{post.title}}"></li>
                                <li class="author list-inline-item">@{{post.author.username}}</li>
                            </ul>
                            
                            <small class="py-3"> 
                                {% for t in post.tags.all %}
                                <a href="{% url 'posts:post_tag_list' t %}">
                                    <span class="badge bg-success">#{{t}}</span>
                                </a>
                                {% endfor %}
                            </small>
                            <div class="row mt-3">
                            <div class="col-6">
                                {% if request.user.is_authenticated %}
                                    {% if post.id in already_liked %}
                                        <a name="{{post.id}}" class="latest-likin" id="co" style="color: blue;"><i class="fa fa-thumbs-o-up me-2"></i></a><span class="me-3 likes-count-{{post.id}}">{{post.total_likes}}</span>
                                    {% else %}
                                        <a name="{{ post.id }}" style="color: black;" class="latest-likin" id="co"><i class="fa fa-thumbs-o-up me-2" aria-hidden="true"></i></a><span class="me-3 likes-count-{{post.id}}">{{post.total_likes}}</span>
                                    {% endif %}
                                {% else %}
                                    <a name="{{ post.id }}" style="color: black;" class="latest-likin" href="{% url 'account_login' %}" id="co"><i class="fa fa-thumbs-o-up me-2" aria-hidden="true"></i></a><span class="me-3 likes-count-{{post.id}}">{{post.total_likes}}</span>
                                {% endif %}


                                <a><i class="fa fa-comments-o me-2"></i> {% get_comments_count post user %} </a>
                            </div>
                            <div class="col-6">
                                <div class="d-flex d-flex justify-content-end">
                                    <small class="text-muted me-2">{{post.view_count}} <i class="fa fa-eye"></i></small>
                                    <small class="text-muted me-3">{{post.get_readtime}} read</small>
                                </div>
                            </div>
                            </div>
                        
                        </div>                   
                    </div>
                </a>
                {% endfor %}
            </div>
            <div class="col-lg-3 my-3">
                <div class="card">
                    <div class="card-body bg-maroon text-light">
                        <h1 class="my-3">Sogea<br>Newsletter</h1>
                        <p>Join the newsletter to receive the latest updates in your inbox.</p>
                        <form method="POST" action="{% url 'marketing:email-list-signup' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                {% render_field form.email class="form-control" placeholder="Your Email Address" %}
                                <div class="d-grid gap-2 my-3">
                                    <button type="submit" class="btn btn-dark py-2">Subscribe</button>
                                </div> 
                            </div>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
      
    </div>

  </main>
{% endblock %}

{% block javascript %}

<script>
    // AJAX CALL - Featured Post
    $('.likin').click(function(){
        var postID = $(this).attr('name');
        console.log(postID);

        $.ajax({
            type: "POST",
            url: "{% url 'posts:save_likes' %}",
            data: {'content_id': $(this).attr('name'),'operation':'like_submit','csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType: "json",
            success: function(response) {
            selector = document.getElementsByName(response.content_id);

            var _prevlike=$(".like-count-"+postID).text();

            console.log(_prevlike)

                if(response.liked==true){
                    $(selector).css("color","blue");
                    $(".like-count-"+postID).text(parseInt(_prevlike)+1);  
                }
                else if(response.liked==false){
                    $(selector).css("color","black");
                    $(".like-count-"+postID).text(parseInt(_prevlike)-1);
                }
            }
        });
    })
</script>

<script>
    // AJAX CALL - Latest Post
    $('.latest-likin').click(function(){
        var postID = $(this).attr('name');
        console.log(postID);

        $.ajax({
            type: "POST",
            url: "{% url 'posts:save_likes' %}",
            data: {'content_id': $(this).attr('name'),'operation':'like_submit','csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType: "json",
            success: function(response) {
            selector = document.getElementsByName(response.content_id);

            var _prevlike=$(".likes-count-"+postID).text();

            console.log(_prevlike)

                if(response.liked==true){
                    $(selector).css("color","blue");
                    $(".likes-count-"+postID).text(parseInt(_prevlike)+1);  
                }
                else if(response.liked==false){
                    $(selector).css("color","black");
                    $(".likes-count-"+postID).text(parseInt(_prevlike)-1);
                }
            }
        });
    })
</script>

{% endblock javascript %}